@extends('layouts.dashboard')

@section('title', 'Reports & Analytics | AutoProject+')

@section('content')
<div
    x-data="{
        showDateRangeModal: false,
        showExportAllDropdown: false,
        preset: '{{ $preset }}',
        startDate: '{{ $startDateParam ?? '' }}',
        endDate: '{{ $endDateParam ?? '' }}',

        printPage() {
            window.print();
        },

        setPreset(p) {
            this.preset = p;
            if (p !== 'custom') {
                this.$nextTick(() => {
                    this.$refs.filterForm.submit();
                });
            }
        }
    }"
    class="space-y-6"
>
    {{-- Printable Header (Visible only when printing) --}}
    <div class="hidden print:block mb-6 border-b-2 border-[#E63946] pb-4">
        <div class="flex justify-between items-start">
            <div>
                <h1 class="text-3xl font-bold text-gray-900 tracking-wider">AUTO<span class="text-[#E63946]">PROJECT</span>+</h1>
                <p class="text-xs text-gray-500 font-semibold uppercase tracking-widest mt-1">Official Executive Reports & Business Analytics</p>
            </div>
            <div class="text-right text-xs text-gray-600 space-y-1">
                <p><span class="font-bold text-gray-800">Date Range Criteria:</span> {{ $dateRangeLabel }}</p>
                <p><span class="font-bold text-gray-800">Date Printed:</span> {{ now()->format('F j, Y h:i A') }}</p>
                <p><span class="font-bold text-gray-800">Generated By:</span> {{ auth()->user()->name ?? 'Chief Admin' }}</p>
            </div>
        </div>
    </div>

    {{-- Header --}}
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 no-print">
        <div>
            <h1 class="text-3xl font-bold text-gray-900 dark:text-white mb-2">Reports & Analytics</h1>
            <p class="text-gray-600 dark:text-gray-400">Comprehensive business insights and performance metrics.</p>
        </div>
        <div class="flex items-center gap-3">
            {{-- Date Range Button --}}
            <x-button variant="secondary" size="sm" @click="showDateRangeModal = true">
                <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
                <span>Date Range: <strong class="text-[#E63946] dark:text-[#E63946]">{{ $dateRangeLabel }}</strong></span>
            </x-button>

            {{-- Export All Dropdown Button --}}
            <div class="relative">
                <x-button variant="accent" size="sm" @click="showExportAllDropdown = !showExportAllDropdown">
                    <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Export All
                    <svg class="w-3.5 h-3.5 ml-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
                </x-button>

                <div
                    x-show="showExportAllDropdown"
                    x-cloak
                    @click.away="showExportAllDropdown = false"
                    class="absolute right-0 mt-2 w-56 rounded-xl bg-white dark:bg-[#1E1E1E] shadow-xl border border-gray-200 dark:border-white/10 py-2 z-30"
                >
                    <button
                        type="button"
                        @click="showExportAllDropdown = false; printPage();"
                        class="w-full flex items-center gap-2.5 px-4 py-2.5 text-xs font-semibold text-gray-800 dark:text-white hover:bg-gray-100 dark:hover:bg-white/5 transition"
                    >
                        <svg class="w-4 h-4 text-[#E63946]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
                        Print Report / Save PDF
                    </button>
                    <a
                        href="{{ route('admin.reports.index', array_merge(request()->query(), ['export' => 'all'])) }}"
                        @click="showExportAllDropdown = false"
                        class="w-full flex items-center gap-2.5 px-4 py-2.5 text-xs font-semibold text-gray-800 dark:text-white hover:bg-gray-100 dark:hover:bg-white/5 transition"
                    >
                        <svg class="w-4 h-4 text-[#457B9D]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
                        Download Full CSV Data
                    </a>
                </div>
            </div>
        </div>
    </div>

    {{-- Key Metrics Grid --}}
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 text-white">
        <x-card class="bg-gradient-to-br from-[#E63946] to-[#D62839] border-transparent shadow-lg p-6">
            <p class="text-white/80 text-sm mb-1">Finalized Billing Revenue</p>
            <p class="text-3xl font-bold">₱{{ number_format($totalFinalizedRevenue, 2) }}</p>
            <p class="text-xs text-white/70 mt-1">Locked customer billing total</p>
        </x-card>

        <x-card class="bg-gradient-to-br from-[#457B9D] to-[#5A8FB0] border-transparent shadow-lg p-6">
            <p class="text-white/80 text-sm mb-1">Total Payments Collected</p>
            <p class="text-3xl font-bold">₱{{ number_format($totalRevenue, 2) }}</p>
            <p class="text-xs text-white/70 mt-1">Reservation fees: ₱{{ number_format($reservationFeesCollected, 2) }}</p>
        </x-card>

        <x-card class="bg-gradient-to-br from-amber-500 to-amber-600 border-transparent shadow-lg p-6">
            <p class="text-white/80 text-sm mb-1">Outstanding Balances</p>
            <p class="text-3xl font-bold">₱{{ number_format($outstandingBalances, 2) }}</p>
            <p class="text-xs text-white/70 mt-1">Unsettled accounts receivable</p>
        </x-card>

        <x-card class="bg-gradient-to-br from-green-500 to-green-600 border-transparent shadow-lg p-6">
            <p class="text-white/80 text-sm mb-1">Completion Rate</p>
            <p class="text-3xl font-bold">{{ $completionRate }}%</p>
            <p class="text-xs text-white/70 mt-1">Total Bookings: {{ $totalBookings }}</p>
        </x-card>
    </div>

    {{-- Monthly Revenue & Bookings Area Chart --}}
    <x-card>
        <div class="flex justify-between items-center mb-6">
            <h2 class="text-xl font-bold text-gray-900 dark:text-white">Monthly Revenue & Bookings</h2>

            <div class="relative no-print" x-data="{ open: false }">
                <x-button variant="ghost" size="sm" @click="open = !open">
                    <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Export
                </x-button>
                <div
                    x-show="open"
                    x-cloak
                    @click.away="open = false"
                    class="absolute right-0 mt-2 w-48 rounded-xl bg-white dark:bg-[#1E1E1E] shadow-xl border border-gray-200 dark:border-white/10 py-1.5 z-20"
                >
                    <button
                        type="button"
                        @click="open = false; printPage();"
                        class="w-full flex items-center gap-2 px-3.5 py-2 text-xs font-semibold text-gray-800 dark:text-white hover:bg-gray-100 dark:hover:bg-white/5 transition"
                    >
                        <svg class="w-4 h-4 text-[#E63946]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
                        Print Section
                    </button>
                    <a
                        href="{{ route('admin.reports.index', array_merge(request()->query(), ['export' => 'revenue'])) }}"
                        @click="open = false"
                        class="w-full flex items-center gap-2 px-3.5 py-2 text-xs font-semibold text-gray-800 dark:text-white hover:bg-gray-100 dark:hover:bg-white/5 transition"
                    >
                        <svg class="w-4 h-4 text-[#457B9D]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
                        Download CSV Data
                    </a>
                </div>
            </div>
        </div>
        <div x-data="{
            init() {
                const ctx = document.getElementById('monthlyRevenueBookingsChart').getContext('2d');

                const gradRevenue = ctx.createLinearGradient(0, 0, 0, 350);
                gradRevenue.addColorStop(0, 'rgba(230, 57, 70, 0.4)');
                gradRevenue.addColorStop(1, 'rgba(230, 57, 70, 0)');

                const gradBookings = ctx.createLinearGradient(0, 0, 0, 350);
                gradBookings.addColorStop(0, 'rgba(69, 123, 157, 0.4)');
                gradBookings.addColorStop(1, 'rgba(69, 123, 157, 0)');

                new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: @js($months),
                        datasets: [
                            {
                                label: 'Revenue (₱)',
                                data: @js($revenueData),
                                borderColor: '#E63946',
                                backgroundColor: gradRevenue,
                                borderWidth: 3,
                                fill: true,
                                tension: 0.3,
                                yAxisID: 'yRevenue'
                            },
                            {
                                label: 'Bookings',
                                data: @js($bookingsData),
                                borderColor: '#457B9D',
                                backgroundColor: gradBookings,
                                borderWidth: 3,
                                fill: true,
                                tension: 0.3,
                                yAxisID: 'yBookings'
                            }
                        ]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                labels: { color: '#6b7280' }
                            },
                            tooltip: {
                                callbacks: {
                                    label: function(context) {
                                        let label = context.dataset.label || '';
                                        if (label) {
                                            label += ': ';
                                        }
                                        if (context.datasetIndex === 0) {
                                            label += '₱' + context.raw.toLocaleString();
                                        } else {
                                            label += context.raw;
                                        }
                                        return label;
                                    }
                                }
                            }
                        },
                        scales: {
                            x: {
                                grid: { display: false },
                                ticks: { color: '#6b7280' }
                            },
                            yRevenue: {
                                type: 'linear',
                                display: true,
                                position: 'left',
                                grid: { color: 'rgba(107, 114, 128, 0.1)' },
                                ticks: {
                                    color: '#6b7280',
                                    callback: function(value) {
                                        return '₱' + (value / 1000) + 'K';
                                    }
                                }
                            },
                            yBookings: {
                                type: 'linear',
                                display: true,
                                position: 'right',
                                grid: { drawOnChartArea: false },
                                ticks: { color: '#6b7280' }
                            }
                        }
                    }
                });
            }
        }" class="h-[350px] relative">
            <canvas id="monthlyRevenueBookingsChart"></canvas>
        </div>
    </x-card>

    {{-- Service Popularity Horizontal Bar Chart --}}
    <x-card>
        <div class="flex justify-between items-center mb-6">
            <h2 class="text-xl font-bold text-gray-900 dark:text-white">Service Popularity</h2>

            <div class="relative no-print" x-data="{ open: false }">
                <x-button variant="ghost" size="sm" @click="open = !open">
                    <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Export
                </x-button>
                <div
                    x-show="open"
                    x-cloak
                    @click.away="open = false"
                    class="absolute right-0 mt-2 w-48 rounded-xl bg-white dark:bg-[#1E1E1E] shadow-xl border border-gray-200 dark:border-white/10 py-1.5 z-20"
                >
                    <button
                        type="button"
                        @click="open = false; printPage();"
                        class="w-full flex items-center gap-2 px-3.5 py-2 text-xs font-semibold text-gray-800 dark:text-white hover:bg-gray-100 dark:hover:bg-white/5 transition"
                    >
                        <svg class="w-4 h-4 text-[#E63946]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
                        Print Section
                    </button>
                    <a
                        href="{{ route('admin.reports.index', array_merge(request()->query(), ['export' => 'popularity'])) }}"
                        @click="open = false"
                        class="w-full flex items-center gap-2 px-3.5 py-2 text-xs font-semibold text-gray-800 dark:text-white hover:bg-gray-100 dark:hover:bg-white/5 transition"
                    >
                        <svg class="w-4 h-4 text-[#457B9D]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
                        Download CSV Data
                    </a>
                </div>
            </div>
        </div>
        <div x-data="{
            init() {
                const ctx = document.getElementById('servicePopularityChart').getContext('2d');
                new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: @js($servicePopularityLabels),
                        datasets: [{
                            label: 'Bookings Completed',
                            data: @js($servicePopularityCounts),
                            backgroundColor: '#E63946',
                            borderRadius: 8,
                            borderSkipped: false
                        }]
                    },
                    options: {
                        indexAxis: 'y',
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: { display: false }
                        },
                        scales: {
                            x: {
                                grid: { color: 'rgba(107, 114, 128, 0.1)' },
                                ticks: { color: '#6b7280' }
                            },
                            y: {
                                grid: { display: false },
                                ticks: { color: '#6b7280' }
                            }
                        }
                    }
                });
            }
        }" class="h-[300px] relative">
            <canvas id="servicePopularityChart"></canvas>
        </div>
    </x-card>

    {{-- Customer Activity Trends Line Chart --}}
    <x-card>
        <div class="flex justify-between items-center mb-6">
            <h2 class="text-xl font-bold text-gray-900 dark:text-white">Customer Activity Trends</h2>

            <div class="relative no-print" x-data="{ open: false }">
                <x-button variant="ghost" size="sm" @click="open = !open">
                    <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Export
                </x-button>
                <div
                    x-show="open"
                    x-cloak
                    @click.away="open = false"
                    class="absolute right-0 mt-2 w-48 rounded-xl bg-white dark:bg-[#1E1E1E] shadow-xl border border-gray-200 dark:border-white/10 py-1.5 z-20"
                >
                    <button
                        type="button"
                        @click="open = false; printPage();"
                        class="w-full flex items-center gap-2 px-3.5 py-2 text-xs font-semibold text-gray-800 dark:text-white hover:bg-gray-100 dark:hover:bg-white/5 transition"
                    >
                        <svg class="w-4 h-4 text-[#E63946]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
                        Print Section
                    </button>
                    <a
                        href="{{ route('admin.reports.index', array_merge(request()->query(), ['export' => 'trends'])) }}"
                        @click="open = false"
                        class="w-full flex items-center gap-2 px-3.5 py-2 text-xs font-semibold text-gray-800 dark:text-white hover:bg-gray-100 dark:hover:bg-white/5 transition"
                    >
                        <svg class="w-4 h-4 text-[#457B9D]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
                        Download CSV Data
                    </a>
                </div>
            </div>
        </div>
        <div x-data="{
            init() {
                const ctx = document.getElementById('customerActivityTrendsChart').getContext('2d');
                new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: @js($months),
                        datasets: [
                            {
                                label: 'New Customers',
                                data: @js($newCustomersData),
                                borderColor: '#E63946',
                                backgroundColor: 'transparent',
                                borderWidth: 3,
                                pointBackgroundColor: '#E63946',
                                tension: 0.3
                            },
                            {
                                label: 'Returning Customers',
                                data: @js($returningCustomersData),
                                borderColor: '#457B9D',
                                backgroundColor: 'transparent',
                                borderWidth: 3,
                                pointBackgroundColor: '#457B9D',
                                tension: 0.3
                            }
                        ]
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                labels: { color: '#6b7280' }
                            }
                        },
                        scales: {
                            x: {
                                grid: { display: false },
                                ticks: { color: '#6b7280' }
                            },
                            y: {
                                grid: { color: 'rgba(107, 114, 128, 0.1)' },
                                ticks: { color: '#6b7280' }
                            }
                        }
                    }
                });
            }
        }" class="h-[300px] relative">
            <canvas id="customerActivityTrendsChart"></canvas>
        </div>
    </x-card>

    {{-- Service Performance Summary Table --}}
    <x-card>
        <div class="flex justify-between items-center mb-6">
            <h2 class="text-xl font-bold text-gray-900 dark:text-white">Service Performance Summary</h2>

            <div class="relative no-print" x-data="{ open: false }">
                <x-button variant="ghost" size="sm" @click="open = !open">
                    <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Export
                </x-button>
                <div
                    x-show="open"
                    x-cloak
                    @click.away="open = false"
                    class="absolute right-0 mt-2 w-48 rounded-xl bg-white dark:bg-[#1E1E1E] shadow-xl border border-gray-200 dark:border-white/10 py-1.5 z-20"
                >
                    <button
                        type="button"
                        @click="open = false; printPage();"
                        class="w-full flex items-center gap-2 px-3.5 py-2 text-xs font-semibold text-gray-800 dark:text-white hover:bg-gray-100 dark:hover:bg-white/5 transition"
                    >
                        <svg class="w-4 h-4 text-[#E63946]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/></svg>
                        Print Section
                    </button>
                    <a
                        href="{{ route('admin.reports.index', array_merge(request()->query(), ['export' => 'summary'])) }}"
                        @click="open = false"
                        class="w-full flex items-center gap-2 px-3.5 py-2 text-xs font-semibold text-gray-800 dark:text-white hover:bg-gray-100 dark:hover:bg-white/5 transition"
                    >
                        <svg class="w-4 h-4 text-[#457B9D]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
                        Download CSV Data
                    </a>
                </div>
            </div>
        </div>
        <div class="p-0 overflow-hidden rounded-xl border border-gray-200 dark:border-white/10">
            <x-table>
                <x-table-header>
                    <x-table-row>
                        <x-table-head>Service</x-table-head>
                        <x-table-head>Bookings</x-table-head>
                        <x-table-head>Revenue</x-table-head>
                        <x-table-head>Avg. Value</x-table-head>
                        <x-table-head>Trend</x-table-head>
                    </x-table-row>
                </x-table-header>
                <x-table-body>
                    @foreach ($servicePerformance as $service)
                        <x-table-row>
                            <x-table-cell>
                                <span class="font-semibold text-gray-900 dark:text-white">{{ $service['name'] }}</span>
                            </x-table-cell>
                            <x-table-cell>
                                <span class="text-gray-600 dark:text-gray-400">{{ $service['bookings'] }}</span>
                            </x-table-cell>
                            <x-table-cell>
                                <span class="text-gray-600 dark:text-gray-400">₱{{ number_format($service['revenue']) }}</span>
                            </x-table-cell>
                            <x-table-cell>
                                <span class="text-gray-600 dark:text-gray-400">₱{{ number_format($service['avg']) }}</span>
                            </x-table-cell>
                            <x-table-cell>
                                <span class="text-green-500 font-semibold flex items-center gap-1">
                                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                                    </svg>
                                    {{ $service['trend'] }}
                                </span>
                            </x-table-cell>
                        </x-table-row>
                    @endforeach
                </x-table-body>
            </x-table>
        </div>
    </x-card>

    {{-- Printable Signature Footer --}}
    <div class="hidden print:block mt-12 pt-6 border-t border-gray-300">
        <div class="grid grid-cols-2 gap-12 text-xs text-gray-700">
            <div>
                <p class="font-semibold mb-10">Prepared By:</p>
                <div class="border-b border-gray-400 w-56 mb-1"></div>
                <p class="font-bold text-gray-900">{{ auth()->user()->name ?? 'Chief Admin' }}</p>
                <p class="text-gray-500">Chief Admin / System Operator</p>
            </div>
            <div>
                <p class="font-semibold mb-10">Approved & Accepted By:</p>
                <div class="border-b border-gray-400 w-56 mb-1"></div>
                <p class="font-bold text-gray-900">Shop Manager / Adviser</p>
                <p class="text-gray-500">AutoProject+ Management</p>
            </div>
        </div>
    </div>

    {{-- Date Range Modal --}}
    <div
        x-show="showDateRangeModal"
        x-cloak
        class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm no-print"
        @keydown.escape.window="showDateRangeModal = false"
    >
        <div
            class="bg-white dark:bg-[#1E1E1E] rounded-2xl shadow-2xl border border-gray-200 dark:border-white/10 w-full max-w-md p-6 space-y-5"
            @click.away="showDateRangeModal = false"
        >
            <div class="flex justify-between items-center border-b border-gray-100 dark:border-white/10 pb-3">
                <h3 class="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
                    <x-icon name="calendar" class="w-5 h-5 text-[#E63946]" />
                    Filter Date Range
                </h3>
                <button @click="showDateRangeModal = false" class="text-gray-400 hover:text-gray-600 dark:hover:text-white">
                    <x-icon name="x" class="w-5 h-5" />
                </button>
            </div>

            <form x-ref="filterForm" method="GET" action="{{ route('admin.reports.index') }}" class="space-y-4">
                <input type="hidden" name="preset" :value="preset" />

                <div>
                    <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Quick Presets</label>
                    <div class="grid grid-cols-2 gap-2">
                        <button type="button" @click="setPreset('all')" :class="preset === 'all' ? 'bg-[#E63946] text-white' : 'bg-gray-100 dark:bg-white/5 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-white/10'" class="px-3 py-2 rounded-xl text-xs font-semibold transition">
                            All Time
                        </button>
                        <button type="button" @click="setPreset('today')" :class="preset === 'today' ? 'bg-[#E63946] text-white' : 'bg-gray-100 dark:bg-white/5 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-white/10'" class="px-3 py-2 rounded-xl text-xs font-semibold transition">
                            Today
                        </button>
                        <button type="button" @click="setPreset('this_month')" :class="preset === 'this_month' ? 'bg-[#E63946] text-white' : 'bg-gray-100 dark:bg-white/5 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-white/10'" class="px-3 py-2 rounded-xl text-xs font-semibold transition">
                            This Month
                        </button>
                        <button type="button" @click="setPreset('last_30_days')" :class="preset === 'last_30_days' ? 'bg-[#E63946] text-white' : 'bg-gray-100 dark:bg-white/5 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-white/10'" class="px-3 py-2 rounded-xl text-xs font-semibold transition">
                            Last 30 Days
                        </button>
                        <button type="button" @click="setPreset('last_90_days')" :class="preset === 'last_90_days' ? 'bg-[#E63946] text-white' : 'bg-gray-100 dark:bg-white/5 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-white/10'" class="px-3 py-2 rounded-xl text-xs font-semibold transition">
                            Last 90 Days
                        </button>
                        <button type="button" @click="preset = 'custom'" :class="preset === 'custom' ? 'bg-[#E63946] text-white' : 'bg-gray-100 dark:bg-white/5 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-white/10'" class="px-3 py-2 rounded-xl text-xs font-semibold transition">
                            Custom Range
                        </button>
                    </div>
                </div>

                <div x-show="preset === 'custom'" x-collapse class="space-y-3 pt-2 border-t border-gray-100 dark:border-white/10">
                    <div>
                        <label class="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">Start Date</label>
                        <input type="date" name="start_date" x-model="startDate" class="w-full rounded-xl border border-gray-300 dark:border-white/10 bg-white dark:bg-[#151515] px-3 py-2 text-sm text-gray-900 dark:text-white" />
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1">End Date</label>
                        <input type="date" name="end_date" x-model="endDate" class="w-full rounded-xl border border-gray-300 dark:border-white/10 bg-white dark:bg-[#151515] px-3 py-2 text-sm text-gray-900 dark:text-white" />
                    </div>
                </div>

                <div class="flex justify-end gap-2 pt-3 border-t border-gray-100 dark:border-white/10">
                    <button type="button" @click="showDateRangeModal = false" class="px-4 py-2 text-xs font-semibold rounded-xl text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-white/5">
                        Cancel
                    </button>
                    <button type="submit" class="px-5 py-2 text-xs font-semibold rounded-xl text-white bg-[#E63946] hover:bg-[#d62839]">
                        Apply Filter
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<style>
@media print {
    /* Hide all web layout chrome */
    aside, header, nav, button, .no-print, [role="status"], [x-cloak], .toast-container {
        display: none !important;
    }

    body, html {
        background-color: #ffffff !important;
        color: #000000 !important;
        padding: 0 !important;
        margin: 0 !important;
    }

    .lg\:ml-64 {
        margin-left: 0 !important;
    }

    main {
        padding: 1rem !important;
    }

    /* Print color fidelity */
    .bg-gradient-to-br, [class*="bg-"] {
        -webkit-print-color-adjust: exact !important;
        print-color-adjust: exact !important;
    }

    /* Card styling on print */
    .grid > div, x-card, table, canvas {
        page-break-inside: avoid !important;
        break-inside: avoid !important;
    }
}
</style>
@endpush

